create Add and remove function to list
Reem-lab/To-Do-List pull request #3
Opened 2022-01-14 01:17 UTC by Reem-lab

## Changes that I made here 👍 
 - set up the project with my webpack template 
 - Create the Tasks dynamically by input 
 - Add remove trash to remove tasks
 - Add completed and index to the task
 - save them in local storage
 - when you delete the item from the list it deleted from local storage also
 - no linter error
 - Add some styles to my list

2022-01-14 03:33 UTC, rloterh requested changes
Hi Remoz, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦  🚦  

## Good Points 👍 
- Descriptive Pull Request
- No linter errors


## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly check the comments marked **[OPTIONAL]** under the review._
<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-14 03:33 UTC, rloterh commented on src/createList.js
> +// eslint-disable-next-line import/no-mutable-exports
- [ ] OPTIONAL
You have **disabled linter check** on your code. Please enable **all** linter checks on your code to ensure that your code is robust code and clean.

2022-01-14 03:33 UTC, rloterh commented on src/createList.js
> +
- [ ] Editing a list is not working as intended. When a task _one_ is added and then then renamed to _one man_, the changes do not reflect in the local storage. Kindly endeavor to improve upon this aspect.

**Editing / Update error:**
![image](https://user-images.githubusercontent.com/12745474/149446265-cb934706-f5c7-4ab2-95ac-9d5c071a327b.png)

2022-01-14 03:33 UTC, rloterh commented on src/index.html
- [ ] Checked items are not removed from the list/ local storage when the _Clear all completed_ button is clicked. Kindly ensure to improve upon this aspect

2022-01-14 03:33 UTC, rloterh commented on webpack.config.js
>  // import HtmlWebpackPlugin from 'html-webpack-plugin';
- [ ] OPTIONAL
Webpack is not configured properly and hence your application is not working as intended. You can update your webpack to look something similar to this:

```javascript
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  mode: 'development',
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
  module: {
    rules: [{
      test: /\.css$/i,
      use: ['style-loader', 'css-loader'],
    }],
  },
  devServer: {
    contentBase: './dist',
  },

  plugins: [
    new HtmlWebpackPlugin({
      template: './src/index.html',
    }),
  ],
};
```

2022-01-15 03:33 UTC, DanSam5K approved these changes
# Hi @Reem-lab, :v: Approved :v: 
- [x] Good job implementing the changes required of you :heavy_check_mark: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-15 03:41 UTC, merged